### ISSUE TITLE
不知所云

### ISSUE THREAD

**Issue by qx** [windy/ruby-vimrc#3]
东一句西一句,根本不连贯,不适合新手

**Comment by windy** [comment]
@qx 你这个新手很挑嘛. 使用文档里面的第一句就是适合待进阶的 vim 使用者. 不适合初学者.

**Comment by qx** [comment]
呵呵,可能吧.如果能完善一点更好,难怪fork这么少,估计上手比较难

**Comment by windy** [comment]
@qx 你觉得 vim 基本操作用的挺熟了, 但还没有那么溜的时候, 这个文档就很有帮助. 文档反响还是非常好的当时.

另外, 不是每一个开源项目都是以 star 与 fork 为目标哈, 只要有价值就足够了.

**Comment by qx** [comment]
嗯,能共享出来就是好的.
另外这个里面常用的一些快捷键,功能命令能说一下么?完全一头雾水,好东西对我这样的人也发现不了..
